http://localhost:8080/calculator
###
http://localhost:8080/calculator/divide?num1=5&num2=2
###
http://localhost:8080/calculator/plus?num1=5&num2=2
###
http://localhost:8080/calculator/divide?num1=5&num2=0
###
http://localhost:8080/calculator/divide?num1=df&num2=3